import Link from "next/link";
import { notFound } from "next/navigation";
import type { Metadata } from "next";
import { destinations, getDestination } from "@/app/content/destinations";
import { hotels } from "@/app/content/hotels";
import s from "@/app/components/public/pages.module.css";
import n from "@/app/components/public/public.module.css";
import u from "@/app/components/ui/ui.module.css";

/**
 * Single trip page.
 *
 * `params` is a Promise in Next 16 — synchronous access was removed in this
 * major, so it has to be awaited both here and in generateMetadata. The
 * `PageProps<'/destinations/[slug]'>` helper is generated by `next typegen`
 * and gives `slug` its type for free.
 */

export async function generateMetadata(
  props: PageProps<"/destinations/[slug]">
): Promise<Metadata> {
  const { slug } = await props.params;
  const trip = getDestination(slug);

  if (!trip) return { title: "Trip not found" };

  return {
    title: `${trip.name} — ${trip.nights} nights`,
    description: trip.tagline,
  };
}

/** Pre-render the six known trips at build time. */
export function generateStaticParams() {
  return destinations.map((d) => ({ slug: d.id }));
}

export default async function DestinationDetail(
  props: PageProps<"/destinations/[slug]">
) {
  const { slug } = await props.params;
  const trip = getDestination(slug);

  // Anything that isn't one of our six slugs is a 404, not an empty page.
  if (!trip) notFound();

  const stays = hotels.filter((h) => h.destinationId === trip.id);

  return (
    <article>
      <div className={s.detailHero}>
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img src={trip.images[0]} alt={trip.name} />
        <div className={s.detailHeroCopy}>
          <div className={s.wrap}>
            <p className={s.eyebrow}>{trip.region}</p>
            <h1 className={s.h1}>{trip.name}</h1>
          </div>
        </div>
      </div>

      <div className={s.wrap}>
        <div className={s.detailGrid}>
          <div>
            <Link href="/destinations" className={s.backLink}>
              &larr; All destinations
            </Link>

            <div className={s.prose}>
              <p>{trip.summary}</p>
            </div>

            <ul className={s.chips} style={{ marginBottom: 34 }}>
              {trip.highlights.map((h) => (
                <li key={h} className={s.chip}>
                  {h}
                </li>
              ))}
            </ul>

            <section className={s.section}>
              <h2 className={s.h2}>Day by day</h2>
              <ol className={s.itinerary}>
                {trip.itinerary.map((day) => (
                  <li key={day.day} className={s.itDay}>
                    <span className={s.itNum}>Day {day.day}</span>
                    <div>
                      <h3 className={s.itTitle}>{day.title}</h3>
                      <p className={s.itDetail}>{day.detail}</p>
                    </div>
                  </li>
                ))}
              </ol>
            </section>

            <section className={s.section}>
              <div className={s.twoCol}>
                <div>
                  <h2 className={s.h2}>What&rsquo;s included</h2>
                  <ul className={s.checkList}>
                    {trip.included.map((item) => (
                      <li key={item}>
                        <span className={s.tick} aria-hidden="true">
                          &#10003;
                        </span>
                        {item}
                      </li>
                    ))}
                  </ul>
                </div>
                <div>
                  <h2 className={s.h2}>Not included</h2>
                  <ul className={s.checkList}>
                    {trip.notIncluded.map((item) => (
                      <li key={item}>
                        <span className={s.cross} aria-hidden="true">
                          &minus;
                        </span>
                        {item}
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            </section>

            {trip.images.length > 1 && (
              <section className={s.section}>
                <h2 className={s.h2}>Photos</h2>
                <div className={u.gallery}>
                  {trip.images.map((src, i) => (
                    <figure className={u.shot} key={src}>
                      {/* eslint-disable-next-line @next/next/no-img-element */}
                      <img
                        src={src}
                        alt={`${trip.name} — view ${i + 1}`}
                        loading="lazy"
                      />
                    </figure>
                  ))}
                </div>
              </section>
            )}

            {stays.length > 0 && (
              <section className={s.section}>
                <h2 className={s.h2}>Where you&rsquo;ll stay</h2>
                <div className={s.hotelGrid}>
                  {stays.map((h) => (
                    <div className={s.hotelCard} key={h.id}>
                      <div className={s.hotelMedia}>
                        {/* eslint-disable-next-line @next/next/no-img-element */}
                        <img src={h.image} alt={h.name} loading="lazy" />
                      </div>
                      <div className={s.hotelBody}>
                        <div>
                          <h3 className={s.tripName}>{h.name}</h3>
                          <span className={s.tripRegion}>{h.location}</span>
                        </div>
                        <p className={s.hotelBlurb}>{h.blurb}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </section>
            )}
          </div>

          <aside className={s.aside}>
            {/* Where the price used to be. A fixed number was never true of
                these trips anyway — the quote depends on the group, the dates
                and how much of the route you want. */}
            <p className={s.asideLead}>Tailor-made</p>
            <p className={s.asideNote}>
              Quoted per party once we know your dates and how many of you are
              travelling. Any of it can be lengthened, shortened or joined to
              another route.
            </p>

            <ul className={s.facts}>
              <li className={s.fact}>
                <span className={s.factLabel}>Duration</span>
                <span className={s.factValue}>{trip.nights} nights</span>
              </li>
              <li className={s.fact}>
                <span className={s.factLabel}>Best months</span>
                <span className={s.factValue}>{trip.bestMonths}</span>
              </li>
              <li className={s.fact}>
                <span className={s.factLabel}>Difficulty</span>
                <span className={s.factValue}>{trip.difficulty}</span>
              </li>
              <li className={s.fact}>
                <span className={s.factLabel}>Rating</span>
                <span className={s.factValue}>{trip.rating.toFixed(1)} / 5</span>
              </li>
            </ul>

            <Link
              href={`/book?trip=${trip.id}`}
              className={`${n.btn} ${n.btnPrimary} ${s.asideBtn}`}
            >
              Request this trip
            </Link>
          </aside>
        </div>
      </div>
    </article>
  );
}
